@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyRecipeBook" as ReadOnlyRecipeBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model_
Class RecipeBook
Class ModelManager
Class UserPrefs

Class UniqueRecipeList
Class Recipe
Class RecipePortion
Class Name
Class RecipeDuration
Class Tag
Class Step
Class Ingredient
Class IngredientParser
Class IngredientBuilder
Class IngredientQuantifier
}

Class HiddenOutside #FFFFFF

HiddenOutside .down.> Model_

ModelManager .up.|> Model_
RecipeBook .up.|> ReadOnlyRecipeBook

Model_ .left.> ReadOnlyUserPrefs
Model_ .right.> ReadOnlyRecipeBook
ModelManager -left-> "1" RecipeBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

RecipeBook *--> "1" UniqueRecipeList
UniqueRecipeList --> "~* all" Recipe
Recipe *--> "1" Name
Recipe *--> "0..1" RecipeDuration
Recipe *--> "0..1" RecipePortion
Recipe *--> "*" Tag
Recipe *--> "*" Step
Recipe *--> "*" Ingredient
Ingredient .up.> IngredientBuilder

Ingredient -left-> "1" IngredientQuantifier
IngredientQuantifier .up.> IngredientBuilder
IngredientBuilder .up.> IngredientParser

ModelManager -->"~* filtered" Recipe
@enduml
